export const dir_latest = `Screenshots/ulatest`;

export const factionNames = ['automaton', 'terminid', 'illuminate'];
export const difficulties = ["SUICIDE MISSION", "IMPOSSIBLE", "HELLDIVE", "SUPER HELLDIVE"];

export const loadoutCrops = [
    [
        { x: 526, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 611, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 696, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 781, y: 844, regionWidth: 66, regionHeight: 66 }
    ],
    [
        { x: 987, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 1072, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 1157, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 1242, y: 844, regionWidth: 66, regionHeight: 66 }
    ],
    [
        { x: 1452, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 1537, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 1622, y: 844, regionWidth: 66, regionHeight: 66 },
        { x: 1707, y: 844, regionWidth: 66, regionHeight: 66 }
    ]
];

export const weaponsCrops = [
    // [
    //     { x: 64, y: 829, regionWidth: 112, regionHeight: 78 },
    //     { x: 209, y: 829, regionWidth: 112, regionHeight: 78 },
    //     { x: 354, y: 829, regionWidth: 112, regionHeight: 78 },
    // ],
    // [
    //     { x: 527, y: 829, regionWidth: 112, regionHeight: 78 },
    //     { x: 989, y: 829, regionWidth: 112, regionHeight: 78 },
    //     { x: 1454, y: 829, regionWidth: 112, regionHeight: 78 },
    // ],
    [
        { x: 673, y: 829, regionWidth: 112, regionHeight: 78 },
        { x: 1134, y: 829, regionWidth: 112, regionHeight: 78 },
        { x: 1599, y: 829, regionWidth: 112, regionHeight: 78 },
    ],
    [
        { x: 818, y: 829, regionWidth: 112, regionHeight: 78 },
        { x: 1279, y: 829, regionWidth: 112, regionHeight: 78 },
        { x: 1744, y: 829, regionWidth: 112, regionHeight: 78 },
    ]
];

export const briefingAreas = [
    { left: 123, top: 5, width: 410, height: 45 }, //planet name
    { left: 124, top: 211, width: 380, height: 25 }, //mission type
    { left: 885, top: 865, width: 215, height: 45 }, //difficulty
    { left: 135, top: 900, width: 34, height: 16 }, //player levels
    { left: 135, top: 835, width: 34, height: 16 }, //player levels
    { left: 135, top: 770, width: 34, height: 16 }, //player levels
    //{ left: 1575, top: 750, width: 260, height: 250 }, //modifiers
];

export const playerLvlAreas = [
    { left: 136, top: 900, width: 32, height: 16 },
    { left: 136, top: 835, width: 32, height: 16 },
    { left: 136, top: 770, width: 32, height: 16 },
];

export const playerLvlAreasBackup = [
    { left: 95, top: 845, width: 70, height: 15 },
    { left: 95, top: 780, width: 70, height: 15 },
    { left: 95, top: 715, width: 70, height: 15 },
];


export const briefingColorCoords = [
    { left: 84, top: 900 },
    { left: 84, top: 830 },
    { left: 84, top: 760 },
]

export const loadoutColorCoords = [
    { left: 585, top: 205 },
    { left: 1046, top: 205 },
    { left: 1510, top: 205 },
]

export const playerColors = [
    { r: 248, g: 138, b: 255 },//purple
    { r: 110, g: 215, b: 85 },//green
    { r: 255, g: 157, b: 68 },//orange
    { r: 129, g: 172, b: 255 },//blue
]

export const primariesNames = {
    "AR-23": "liberator",
    "AR-23P": "liberator_pen",
    "AR-23C": "liberator_conc",
    "AR-23A": "liberator_car",
    "AR-32": "pacifier",
    "StA-52": "sta_52",
    "AR-61": "tenderizer",
    "BR-14": "adjucator",
    "R-2124": "constitution",
    "R-2": "amendment",
    "R-63": "diligence",
    "R-63CS": "diligence_cs",
    "PLAS-39": "accelerator",
    "MP-98": "knight",
    "StA-11": "sta_11",
    "SMG-32": "reprimand",
    "SMG-37": "defender",
    "SMG-72": "pummeler",
    "SG-8": "punisher",
    "SG-8S": "slugger",
    "SG-20": "halt",
    "SG-451": "cookout",
    "SG-225": "breaker",
    "SG-225SP": "spray_n_pray",
    "SG-225IE": "breaker_inc",
    "CB-9": "crossbow",
    "R-36": "eruptor",
    "SG-8P": "punisher_plas",
    "ARC-12": "blitzer",
    "LAS-5": "scythe",
    "LAS-16": "sickle",
    "LAS-17": "sickle_d",
    "PLAS-1": "scorcher",
    "PLAS-101": "purifier",
    "FLAM-66": "torcher",
    "JAR-5": "dominator",
    "R-6": "deadeye",
    "VG-70": "variable",
    "M7S": "m7s",
    "MA5C": "ma5c",
    "M90A": "m90a",
    "AR-2": "coyote",
    "AR/GL-21": "one_two",
    "DBS-2": "double_freedom",
    "R-72": "censor",
    "AR-59": "suppressor",
    "LAS-13": "trident",
    "SG-97": "sweeper",
    "SMG/FLAM-34": "stoker",
    "SMG-203": "gallant",
    "R/40-K": "hot_shot"
};

export const secondariesNames = {
    "P-2": "peacemaker",
    "P-19": "redeemer",
    "P-113": "verdict",
    "P-4": "senator",
    "LAS-58": "talon",
    "P-92": "warrant",
    "CQC-2": "sabre",
    "cQacCc-2": "sabre",
    "CQC-19": "shock_lance",
    "CQC-30": "shock_batton",
    "CQC-5": "axe",
    "P-11": "stim_pistol",
    "SG-22": "bushwacker",
    "P-72": "crisper",
    "GP-31": "grenade_pistol",
    "LAS-7": "laser_pistol",
    "GP-20": "ultimatum",
    "PLAS-15": "loyalist",
    "M6C/SOCOM": "m6c",
    "CQC-42": "machete",
    "P-35": "re_educator",
    "CQC-72": "entrenchment_tool",
    "P-69": "veto",
    "P-33": "missile_pistol",
    "P/40-K": "bolt_pistol"
}

export const throwablesNames = {
    "G-6": "grenade_frag",
    "G-12": "grenade_he",
    "G-10": "grenade_inc",
    "G-16": "grenade_impact",
    "G-13": "grenade_inc_impact",
    "G-23": "grenade_stun",
    "G-4": "grenade_gas",
    "G-50": "grenade_drone",
    "G-3": "grenade_smoke",
    "G-123": "grenade_termite",
    "K-2": "throwing_knife",
    "TED-63": "dynamite",
    "G-142": "grenade_pyro",
    "G-109": "urchin",
    "G-31": "grenade_arc",
    "G-7": "pineapple",
    "TM-1": "lure_mine",
    "G-89": "grenade_smokescreen",
    "G/SH-39": "grenade_shield",
    "G-48": "giga_grenade",
    "G/40-K": "melta_mine"
}

export const armorNames = [
    'Servo-Assisted',
    'Fortified',
    'Extra Padding',
    'Med-Kit',
    'Engineering Kit',
    'Inflammable',
    'Advanced Filtration',
    'Siege-Ready',
    'Gunslinger',
    'Democracy Protects',
    'Scout',
    'Electrical Conduit',
    'Unflinching',
    'Acclimated',
    'Integrated Explosives',
    'Reinforced Epaulettes',
    'Peak Physique',
    'Ballistic Padding',
    'Adreno-Defibrillator',
    'Feet First',
    'Desert Stormer',
    'Rock Solid',
    'Reduced Signature',
    'Supplementary Adrenaline',
    'Concussive Padding, Grenadier',
    'Concussive Padding, Hazmat',
    'Concussive Padding, Reinforced',
    "Oxygenator",
    "True Grit"
];

export const subfactionNames = [
    "JET BRIGADE FACTORIES",
    "THE INCENERATION CORPS",
    "CYBORGS",
    "HEAVY ARMOR SURGE",
    "HULK SURGE",
    "RUPTURE STRAIN",
    "PREDATOR STRAIN",
    "SPORE BURST STRAIN",
    "HIVE LORDS",
    "DRAGONROACHES",
    "MINDLESS MASSES",
    "APPROPRIATORS",
    "VOTE SNATCHERS"
];


export const missionNames = [
    [
        "LAUNCH ICBM",
        "ENABLE E-710 EXTRACTION",
        "RETRIEVE VALUABLE DATA",
        "SPREAD DEMOCRACY",
        "PURGE HATCHERIES",
        "NUKE NURSERY",
        "EMERGENCY EVACUATION",
        "CONDUCT GEOLOGICAL SURVEY",
        "DEPLOY DARK FLUID",
        "DESTROY COMMAND BUNKERS",
        "SABOTAGE AIR BASE",
        "FREE COLONY",
        "EVACUATE COLONISTS",
        "RETRIEVE RECON CRAFT INTEL",
        "NEUTRALIZE ORBITAL DEFENSES",
        "ENABLE OIL EXTRACTION",
        "COLLECT METEOROLOGICAL DATA",
        "COLLECT GLOOM SPORE READINGS",
        "EXTRACT RESEARCH PROBE DATA",
        "COLLECT GLOOM-INFUSED OIL",
        "CHART TERMINID TUNNELS",
        "FREE THE CITY",
        "TAKE DOWN OVERSHIP",
        "EVACUATE CITIZENS",
        "RESTORE AIR QUALITY",
        "SABOTAGE SUPPLY BASES",
        "CLEANSE INFESTED DISTRICT",
        "DESTROY SPORE LUNG",
        "EXTRACT E-711",
        "CONDUCT MOBILE E-711 EXTRACTION",
        "RESTART PUMPS",
        "NEUTRALIZE GROUND-TO-ORBIT DEFENSES",
        "HALT CYBORG PRODUCTION",
        "COMMANDO: AQUIRE EVIDENCE",
        "COMMANDO: EXTRACT INTEL",
        "COMMANDO: SECURE BLACK BOX",
        "CONFISCATE ASSETS",
        "DESTROY EXOSPIRE",
        "SABOTAGE ORGO-PLASMA SYNTHESIS",
        "ANNEX UNTAPPED MINERAL SITES",
        "SEIZE INDUSTRIAL COMPLEX",
        "RAPID AQUISITION"
    ],
    [
        "ERADICATE TERMINID SWARM",
        "ERADICATE AUTOMATON FORCES",
        "BLITZ: SEARCH AND DESTROY",
        "BLITZ: DESTROY ILLUMINATE WARP SHIPS",
        "EVACUATE HIGH-VALUE ASSETS",
        "DEFEND EVACUATION SITE",
        "RETRIEVE ESSENTIAL PERSONNEL",
        "BLITZ: SECURE RESEARCH SITE",
        "BLITZ: DESTROY BIO-PROCESSORS",
        "REPEL INVASION FLEET"
    ],
];

export const equipmentConfig = [
    { key: 'primaries', modifier: 0, isArmor: false, set: primariesNames },
    { key: 'secondaries', modifier: 1, isArmor: false, set: secondariesNames },
    { key: 'throwables', modifier: 2, isArmor: false, set: throwablesNames },
    { key: 'armors', modifier: 3, isArmor: true, set: [] }
  ]

export const modifierNames = {
    "COMPLEX": "Complex Strategem Plotting",
    "DEFENCES": "AA Defences",
    "FLUCTUATIONS": "Orbital Fluctuations",
    "GUNSHIP": "Gunship Patrols",
    "SPORES": "Atmospheric Spores",
    "ROVING": "Roving Shriekers",
    "INTERFERENCE": "Atmospheric Interference",
    "POOR": "Poor Intel"
};

// "POLARIS PRIME",
// "ACHERNAR SECUNDUS"

export const factionPlanets = {
    "terminid": [
      "HEETH",
      "TERREK",
      "LUXURIANT",
      "CIRRUS",
      "PHACT BAY",
      "ZYGOS",
      "AZTERRA",
      "ACAMAR IV",
      "OMICRON",
      "TRANDOR",
      "GRAND ERRANT",
      "DARIUS II",
      "BRILLIANCE",
      "BORE ROCK",
      "TURING",
      "NIVEL 43",
      "GAR HAREN",
      "ANGEL'S VENTURE",
      "GACRUX",
      "MERIDIAN BLACK HOLE",
      "ACRUX IX",
      "VELD",
      "ACHERNAR SECUNDUS",
      "CRIMSICA",
      "GATRIA",
      "ACHIRD III",
      "OSHAUNE",
      "PANDION-XXIV",
      "ACRAB XI",
      "HELLMIRE",
      "FORI PRIME",
      "ERATA PRIME",
      "MORADESH",
      "POLARIS PRIME",
      "ESTANU",
      "FENRIR III",
      "INARI",
      "URSICA XI",
      "ALTA V",
      "ESKER",
      "VOLTERRA",
      "ZAGON PRIME",
      "PHERKAD SECUNDUS",
      "PEACOCK",
      "PARTION",
      "SOCORRO III",
      "ERSON SANDS",
      "CARAMOOR",
      "SLIF",
      "CRUCIBLE",
      "KRAKATWO",
      "NUBLARIA I",
      "SULFURA",
      "FORT UNION",
      "FRONTERIA"
    ],
    "automaton": [
      "VERNEN WELLS",
      "AURORA BAY",
      "CHARON PRIME",
      "MARFARK",
      "CHOOHE",
      "MERGA IV",
      "CLASA",
      "MINTORIA",
      "YED PRIOR",
      "AESIR PASS",
      "MENKENT",
      "MOX",
      "CYBERSTAN",
      "WEZEN",
      "CHARBAL-VII",
      "CHOEPESSA IV",
      "PENTA",
      "VOG-SOJOTH",
      "CURIA",
      "FENMIRE",
      "TARSH",
      "MERAK",
      "GAELLIVARE",
      "FURY",
      "ZOSMA",
      "ZEFIA",
      "UBANEA",
      "TIBIT",
      "MARTALE",
      "MALEVELON CREEK",
      "MAIA",
      "CLAORELL",
      "CHORT BAY",
      "INGMAR",
      "MORT",
      "DUMA TYR",
      "JULHEIM",
      "K",
      "ZZANIAH PRIME",
      "X-45",
      "VEGA BAY",
      "WASAT",
      "VARYLIA 5",
      "VANDALON IV",
      "USTOTU",
      "TROOST",
      "TIEN KWAN",
      "MEISSA",
      "MATAR BAY",
      "MANTES",
      "LESATH",
      "DEMIURG",
      "DRAUPNIR",
      "DURGEN",
      "CAPH",
      "BEKVAM III",
      "DOLPH",
      "GUNVALD",
      "PÖPLI IX",
      "OSLO STATION",
      "OUTPOST 32",
      "BLISTICA",
      "IMBER",
      "SHELT",
      "BOREA",
      "SHALLUS",
      "MASTIA",
      "BARABOS",
      "EMERIA"
    ],
    "illuminate": [
      "KEID",
      "HYDROBIUS",
      "HESOE PRIME",
      "SUPER EARTH",
      "GEMMA",
      "KERTH SECUNDUS",
      "RD-4",
      "REAF",
      "NEW STOCKHOLM",
      "ELYSIAN MEADOWS",
      "VALMOX",
      "REGNUS",
      "MOG",
      "HORT",
      "PARSH",
      "HALDUS",
      "OASIS",
      "SIEMNOT",
      "GENESIS PRIME",
      "HERTHON SECUNDUS",
      "IRULTA",
      "RIRGA BAY",
      "ZEA RUGOSIA",
      "ALAMAK VII",
      "SEYSHEL BEACH",
      "HEZE BAY",
      "EUKORIA",
      "AIN-5",
      "PROPUS",
      "ADHARA",
      "TERMADON",
      "STOUT",
      "STOR THA PRIME",
      "SPHERION",
      "SKAT BAY",
      "SIRIUS",
      "SHETE",
      "SETIA",
      "SENGE 23",
      "SEASSE",
      "ROGUE 5",
      "RAS ALGETHI",
      "LENG SCUNDUS",
      "KRAZ",
      "KLAKA 5",
      "KHANDARK",
      "KARLIA",
      "HADAR",
      "CANOPUS",
      "BUNDA SECUNDUS",
      "BRINK-2",
      "OSUPSAM",
      "BOTEIN",
      "BELLATRIX",
      "ASPEROTH PRIME",
      "ANDAR",
      "ALATHFAR XI",
      "ALARAPH",
      "ALAIRT III",
      "AFOYAY BAY",
      "ACUBENS PRIME",
      "BALDRICK PRIME",
      "LIBERTY RIDGE",
      "EAST IRIDIUM TRADING BAY",
      "ALDERIDGE COVE",
      "CALYPSO",
      "GRAFMERE",
      "IRO",
      "BASHYR",
      "RASP",
      "SKAASH",
      "ILDUNA PRIME",
      "EMORATH",
      "MYRIUM",
      "KHARST",
      "EFFLUVIA",
      "PILEN V",
      "NEW HAVEN",
      "WIDOW'S HARBOR",
      "KLEN DAHTH II"
    ]
  }